### ISSUE TITLE
player's health not decreasing in vicinity of zombies

### ISSUE THREAD

**Issue by jollofrice** [TheGloriousGenesis/TheGloriousGenesis-MLGD_SEM1#20]
zombies follow but when they get close the health doesn't decrease

**Comment by TheGloriousGenesis** [comment]
just picked up what's causing the issue, will push changes now!

**Comment by TheGloriousGenesis** [comment]
trigger issue fixed but new health bar doesnt pick up on zombie change so will look into it again

**Comment by TheGloriousGenesis** [comment]
Fixed, also added exception handling so we can check null objects and see where they occur
